Iter13
kirill-chelyatnikov/shortener-url-service pull request #6
Opened 2023-07-20 15:22 UTC by kirill-chelyatnikov

2023-07-26 10:02 UTC, Bazys requested changes
- настроить IDE или githooks на форматирование файлов с помощью goimports или gofumpt
- исправить работу с контекстом.
-  еще парочка вопросов

2023-07-26 10:02 UTC, Bazys commented on internal/app/handlers/url.go
> +	ctx := context.Background()
почему на 17 строчке у тебя корректно берется контекст, а тут Background()?
основная цель контекста, тут, это прервать выполнение sql запроса, если пользователь отменил открытие страницы.
context.Background() - можно брать только один раз, в main, и по необходимости дальше от него наследовать.

2023-07-26 10:02 UTC, Bazys commented on internal/app/handlers/url.go
> +	var result []*APIGETAllResponse
у тебя известна len(links), а размер result в точности равен размеру links, поэтому предлагаю 
```suggestion
	result:=make([]*APIGETAllResponse,0,len(links)
```

2023-07-26 10:02 UTC, Bazys commented on internal/app/handlers/url.go
> +	"context"
импорты не отформатированы.
используй goimports, а еще круче - gofumpt

2023-07-26 10:02 UTC, Bazys commented on internal/app/services/url.go
> +	if err := s.repository.AddURLSBatch(ctx, links); err != nil {
смысл от этой проверки? просто 
```go
return s.repository.AddURLSBatch(ctx, links) 
```

2023-07-26 10:02 UTC, Bazys commented on internal/app/services/url.go
> +	} else {
у тебя строчкой выше return
else здесь совсем без надобности

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/errors.go
> +type DBErrors struct {
в единственном числе

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/storageFile.go
> +func (s *FileStorage) GetAllURLSByHash(ctx context.Context, hash string) ([]*models.Link, error) {
```suggestion
func (s *FileStorage) GetAllURLSByHash(_ context.Context, hash string) ([]*models.Link, error) {
```

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/storageMap.go
> +	s.log.Info(s.data)
зачем тут логирование? может уровень изменить на Debug?

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/storageMap.go
>  	log   *logrus.Logger
посмотри в сторону посовременнее логгеров, типа zap или zerolog

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/storageMap.go
> +	for _, v := range s.data {
зачем этот перебор, у тебя на 22 строке ID является ключом мапы

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/storagePostgreSQL.go
> +func NewPostgreSQLStorage(ctx context.Context, log *logrus.Logger, cfg *config.Config) *PostgreSQLStorage {
посмотри в сторону миграторов, типа go-migrate или goose

2023-07-26 10:02 UTC, Bazys commented on internal/app/storage/storageMap.go
> +			links = append(links, &v)
такое лучше избегать, ты берешь адрес переменной цикла. Это происходит потому, что в операторах for итерационная переменная используется повторно. На каждой итерации переменной итерации присваивается значение очередного элемента в выражении диапазона; v не меняется, меняется только ее значение. Следовательно, выражение &v ссылается на одно и то же место в памяти. Следующий код печатает один и тот же адрес памяти четыре раза: 

```go
for _, n := range []int{1, 2, 3, 4} { 
    fmt.Printf(\"%p\\\n\", &n) 
}
```

короче, это я вный пример неопределенного поведения. Оно может и работает, но может выстрильить непонятно когда и где.
есть несколько способов это избежать

- Использование индекса ранжируемого фрагмента/массива/карты. При этом вместо итерируемой переменной берется адрес фактического элемента в i-й позиции.

```go
for i := range versions { 
    res := createWorkerFor(&versions [i]) 
}
```

- Переназначение итерационной переменной внутри цикла.

```go
for _, v := range versions { 
    v := v  
    res := createWorkerFor(&v) // теперь это адрес внутреннего v 
}
```

- При использовании замыканий передавать итерируемую переменную в качестве аргумента замыкания.

```go
for _, v := range versions { 
    go func (arg ObjectDescription) {  
        x := &arg // safe  
    } (v) 
}
```

2023-08-24 15:17 UTC, kirill-chelyatnikov commented on internal/app/storage/storagePostgreSQL.go
> +func NewPostgreSQLStorage(ctx context.Context, log *logrus.Logger, cfg *config.Config) *PostgreSQLStorage {
Добавил в проект goose, все работает, но не могу теперь автотесты пройти. Жалуется на отсутствие таблицы, автотесты не запускают и не видят миграции

2023-08-24 16:27 UTC, kirill-chelyatnikov commented on internal/app/storage/storagePostgreSQL.go
> +func NewPostgreSQLStorage(ctx context.Context, log *logrus.Logger, cfg *config.Config) *PostgreSQLStorage {
Разобрался вроде

2023-08-27 11:06 UTC, Bazys approved these changes

2023-11-23 12:52 UTC, merged